### PR TITLE
Catch JSON parsing errors

### PR DESCRIPTION
**Pull request by chrismwendt**

### CODE REVIEW

**Comment by chrismwendt** [comment]
I can't seem to sign the CLA. Any ideas?

image

**Comment by chrismwendt** [comment]
Oh, after hitting enter I see this. It might not be set up for this repository yet

image

**Comment by dbaeumer** [comment]
That is strange. Need to look into this. I have no idea since CLA is enabled automatically.

Does this link work for you? https://cla.opensource.microsoft.com/microsoft/vscode-lsif-extension?pullRequest=14

**Comment by dbaeumer** [comment]
Or https://cla.opensource.microsoft.com/microsoft/vscode-lsif-extension

**Comment by dbaeumer** [comment]
I merged the PR by hand. But we should try to find out why you can't sign the CLA

**Pull request closed without merging**
