### PR TITLE
Add type definition/implementation/diagnostic support

### PR DESCRIPTION
**Pull request by jdneo**
Note that the diagnostic informations is only provided on the `OpenTextDocument` event.

### CODE REVIEW

**Comment by dbaeumer** [comment]
@jdalton thanks a lot for the PR and I apologize for the long delay. I have basically rewritten how the extension works to allow different DB backends (not only a JSON structure in memeory). I will release the new code in a couple of day. Would you be willing to adopt your PR. I can do it as well, but I will not be able to simply merge it.

**Comment by jdneo** [comment]
@dbaeumer That's fine, I understand. Looking forward to the new version of the extension.

**Comment by dbaeumer** [comment]
@jdneo a new version of the database is available now. Do you want to look into adjusting the PR.

**Comment by jdneo** [comment]
@dbaeumer Sure. Let me fix the conflicts these days.

**Comment by jdneo** [comment]
Hi @dbaeumer 

I created another new PR: #16. Will close this one.

Thanks,

**Pull request closed without merging**
